version: '3'
services:
    influxdb:
        container_name: influxdb
        image: influxdb:2.5.1
        volumes:
            - "${BACKUP_DIR}/influxv2-data:/var/lib/influxdb2:rw"
            - ./config/influxdb/config.toml:/home/influxdb/.influxdbv2/configs/config.toml:rw
        env_file:
            - ./config/influxdb/influxdb.env
        ports: # [internal container port]:[exposed host port]
            - "8086:8086"
        restart: unless-stopped
    grafana:
        container_name: grafana
        image: grafana/grafana-oss:9.3.1
        volumes:
            - "${BACKUP_DIR}/grafana-data:/var/lib/grafana:rw"
            - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini:rw
        env_file:
            - ./config/grafana/grafana.env
        ports: # [internal container port]:[exposed host port]
            - "3003:3003"
        restart: unless-stopped